#!/usr/bin/python3
def matrix_divided(matrix, div):
    new_matrix = []
    tmp = []
    if type(matrix) != list:
        raise TypeError(
            "matrix must be a matrix (list of lists) of integers/floats")
    if type(div) == float:
        div = int(div)
    elif type(div) != int:
        raise TypeError("div must be a number")
    if div == 0:
        raise ZeroDivisionError("division by zero")
    for idx, row in enumerate(matrix):
        if idx == 0:
            tmp = row
        else:
            if len(tmp) != len(row):
                raise TypeError("Each row of the matrix "
                                "must have the same size")
        for j, elem in enumerate(row):